# Generated by Django 3.2.8 on 2021-10-10 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=254, null=True)),
                ('price_per_m2', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_id', models.CharField(max_length=5)),
                ('type', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('design_surcharge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('example_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('gallery', models.ImageField(blank=True, null=True, upload_to='')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cupboards.material')),
            ],
        ),
    ]
