# Generated by Django 3.2.8 on 2021-10-11 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cupboards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='gallery',
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.ImageField(blank=True, null=True, upload_to='')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cupboards.design')),
            ],
        ),
    ]
