# Generated by Django 3.2.8 on 2021-10-12 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupboards', '0002_auto_20211011_1454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Design',
            new_name='Cupboard',
        ),
        migrations.RenameField(
            model_name='galleryimage',
            old_name='design',
            new_name='cupboard',
        ),
    ]
