# Generated by Django 3.2.8 on 2021-10-16 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cupboards', '0003_auto_20211012_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='material_id',
            new_name='material_code',
        ),
        migrations.AlterField(
            model_name='cupboard',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cupboards.material'),
        ),
    ]
