# Generated by Django 3.2.8 on 2021-10-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupboards', '0005_auto_20211018_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupboard',
            name='type',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
