# Generated by Django 3.2.8 on 2021-10-18 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cupboards', '0006_alter_cupboard_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupboard',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cupboards.type'),
        ),
    ]
