# Generated by Django 3.2.8 on 2021-10-19 11:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cupboards', '0007_alter_cupboard_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='friendly_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cupboard',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cupboards.type'),
        ),
    ]
