# Generated by Django 3.2.8 on 2021-10-19 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupboards', '0008_auto_20211019_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cupboard',
            old_name='example_price',
            new_name='exampleprice',
        ),
    ]
