# Generated by Django 3.2.8 on 2021-10-22 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cupboards', '0009_rename_example_price_cupboard_exampleprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCupboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=254, null=True)),
                ('height', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('width', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('depth', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('shelves', models.IntegerField(null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cupboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cupboards.cupboard')),
            ],
        ),
    ]
