# Generated by Django 3.2.8 on 2021-10-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupboards', '0010_savedcupboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcupboard',
            name='code',
            field=models.IntegerField(null=True),
        ),
    ]
