# Generated by Django 3.2.8 on 2021-10-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupboards', '0011_savedcupboard_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedcupboard',
            name='code',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
