# Generated by Django 3.2.8 on 2021-11-07 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupboards', '0012_alter_savedcupboard_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedCupboard',
        ),
    ]
