# Generated by Django 3.2.8 on 2021-11-09 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupboards', '0013_delete_savedcupboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cupboard',
            old_name='exampleprice',
            new_name='example_price',
        ),
    ]
