# Generated by Django 3.2.8 on 2021-11-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupboards', '0014_rename_exampleprice_cupboard_example_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupboard',
            name='design_id',
            field=models.CharField(max_length=6),
        ),
    ]
