# Generated by Django 3.2.8 on 2021-11-10 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cupboards', '0015_alter_cupboard_design_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupboard',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cupboards.material'),
        ),
    ]
