# Generated by Django 3.2.8 on 2021-11-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupboards', '0017_galleryimage_main_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryImage',
            new_name='Image',
        ),
    ]
