# Generated by Django 3.2.8 on 2021-11-15 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupboards', '0018_rename_galleryimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='material_code',
        ),
    ]
